export interface ISeoModel{
    id: number,
  created: any,
  createdBy?: number,
  active?: boolean,
  modified: any,
  modifiedBy?: number,
  validationErrors?: {},
  PageName: string,
  Title: string,
  Description?: string,
  Keywords: string,
  OGTitle: string,
  OGType: string,
  OGUrl: string,
  OGImage: string,
  OGDescription: string,
  TwitterCard: string,
  TwitterSite: string,
  TwitterTitle: string,
  TwitterDescription: string,
  TwitterImage: string,
  SeocontentTitle:string,
  SeoContent:string
}