export interface IUserModel {
    Id: any,
    Active: true,
    ModifiedBy: number,
    ValidationErrors: {},
    LoginId: any,
    UserRoleId: any,
    UserRoleName: string,
    FirstName: string,
    MiddleName: string,
    LastName: string,
    Email: string,
    Prefix: string,
    Suffix: string,
    DateOfBirth: any,
    UploadImagePath: string,
    UploadImageName: string,
    RowOrder: number,
    Mobile: any,
    SecondaryMobile: any,
    UserLogin: UserLogin,
    Address: any,
    CityId: any,
    PinCode: any,
    StateId: string,
    RoleId: string,
    LocationId: any,
    LocationPin: any,
    PassWord?: any,
    ConfirmPassword?: any,
    Salt: any,
    IVKey: any,
}

export interface UserLogin {
    Id?: any,
    Active?: true,
    ValidationErrors?: {},
    CompanyId?: number,
    UserName?: string,
    PassWord: any,
    Salt: any,
    IVKey: any,
    ConfirmPassword: any,
    RowOrder?: number
}