export interface ISEOModel {
    PageName: string,
    Title: string,
    Description: string,
    Keywords: string,
    OGTitle: string,
    OGType: string,
    OGUrl: string,
    OGImage: string,
    OGDescription: string,
    TwitterCard: string,
    TwitterSite: string,
    TwitterTitle: string,
    TwitterDescription: string,
    TwitterImage: string,
    SeocontentTitle: string,
    SeoContent:string,
    Id: number,
    Created: any,
    CreatedBy: number,
    Active: boolean,
    Modified: any,
    ModifiedBy: number,
    IsValid: boolean,
}
