namespace DOFY.Helper;

public enum ENTITY_TYPE_ENUM
{
    ORDERS = 1,
    PAYMENT = 2,
    CANCELLATION = 3,
    FAILED_ORDERS = 4,
    TESTIMONIAL = 5,
    YOUTUBE = 6,
    HOTSELLING = 7,
    BLOGS = 8,
    RESCHEDULED = 9,
    PRODUCT_VALUE =10,
    THRESHOLD_VALUE = 11,
}