import { getUserLanguage } from "./Helper";

export const HelperConstant = {
    imageAPI: process.env.NEXT_PUBLIC_CDN_URL,
    publicURL: process.env.NEXT_PUBLIC_PUBLIC_URL,
    defaultAPIKey: process.env.NEXT_PUBLIC_PUBLIC_API_KEY,
    osTypeId: { ANDROID: 2, IOS: 3 },
    serviceTypeId: { SELL: 2, REPAIR: 3 },
    roleId: { USER: 4 },
    orderStatus: { InProgress: "In-progress", Pending: "Pending", cancel: "Cancel Requested", failed: "Failed", completed: "Completed", scheduled: "Scheduled", cancelled: "Cancelled" },
    orderStatusId: { InProgress: 3, Pending: 1, cancel: 5, cancelRequest: 14, completed: 9, Scheduled: 2, Rescheduled: 6, Failed: 7, Assigned: 4, Requote: 8, Delayed: 10, Modified: 19 },
    dashboardEntityTypeId: { Testimonial: 5, Youtube: 6, Blogs: 8 },
    emailPattern: { pattern: /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,3})$/ },
    defaultProductTypeId: 12,
    otpVerificationTime: { timer: 120 },
    productTypeId: { phone: 12, TV: 18, smart_watch: 19, gaming_console: 16, earbud: 21, more: 0, desktop: 17, laptop: 13, tablet: 15 },
    productTypeName: [{ Name: "phone" }, { Name: "tablet" }, { Name: "laptop" }, { Name: "smartwatch" }, { Name: "earbud" }, { Name: "gaming-console" }, { Name: "tv" }, { Name: "desktop" }],
    questionnaireType: {
        DeviceDetails: 1,
        FunctionalDetails: 2,
        PossessionDetails: 3,
        DeviceScreenDetails: 4,
        DeviceBodyDetails: 5,
        DeviceAge: 6,
        BillingSection: 7,
        GameCDs: 8,
        PhysicalCondition: 9,
        ScreenCondition: 10,
        SystemConfiguration: 11,
        AdditionalFeatures: 12,
        AdditionalLens: 13
    },
    cancellationList: { othersId: 9 },
    androidAppLink: "https://play.google.com/store/apps/details?id=com.dofy.public",
    iosAppLink: "https://apps.apple.com/us/app/dofy/id1620126058",
    twitterLink: getUserLanguage() == "in_en" ? "https://twitter.com/dofyofficial?s=21&t=bB5ZqG8IPXTU1PC8VZrbNw" : "",
    instagramLink: getUserLanguage() == "in_en" ? "https://www.instagram.com/dofyapp/?igshid=YmMyMTA2M2Y=" : "",
    facebookLink: getUserLanguage() == "in_en" ? "https://www.facebook.com/dofyapp/" : "",
    noVariant: "No Variant",
    noUpdate: "Not Now",
    updateTime: 8,
    metaPages: {
        Home: "Home",
        Device:"Device",
        Brand: "Brand",
        Model:"Model",
        About: "About",
        ContactUs: "ContactUs",
        Faq: "Faq",
        OrderSummary: "OrderSummary",
        PendingOrder:"PendingOrder",
        PrivacyPolicy: "PrivacyPolicy",
        SavedAddress: "SavedAddress",
        Schedule:"Schedule",
        SellDevicedetails:"SellDevicedetails" ,
        SellYourOldDevice: "Device",
        TermsOfUse:"TermsOfUse",
        ViewOrder:"ViewOrder",
        ViewOrderDetails: "ViewOrderDetails",
    }
}